/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon; //importe para la imagen de icono de la pestaña
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author eerix
 */
public class MainGeneral extends javax.swing.JFrame {
    String ruta = null;
    /**
     * Creates new form MainGeneral
     */
    public MainGeneral() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Imagen1.png")).getImage());//Falta cambiar el icono
        setTitle("HELLOWORLD.LPG");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConversacion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldChat = new javax.swing.JTextField();
        jButtonBorrarChat = new javax.swing.JButton();
        jButtonEditarChat = new javax.swing.JButton();
        jButtonCargarArchivo = new javax.swing.JButton();
        jButtonEnviarChat = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabelAdministrador = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelConfirmacion = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblurl = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaConversacion.setColumns(20);
        jTextAreaConversacion.setRows(5);
        jTextAreaConversacion.setText("Estableciendo Conección ...\n");
        jScrollPane1.setViewportView(jTextAreaConversacion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextFieldChat.setText("Conectando ...");
        jTextFieldChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChatActionPerformed(evt);
            }
        });
        jTextFieldChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldChatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldChatKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldChat, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldChat, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        jButtonBorrarChat.setText("BORRAR TODO");
        jButtonBorrarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarChatActionPerformed(evt);
            }
        });

        jButtonEditarChat.setText("EDITAR TEXTO");

        jButtonCargarArchivo.setText("CARGAR ARCHIVO");
        jButtonCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarArchivoActionPerformed(evt);
            }
        });

        jButtonEnviarChat.setText("ENVIAR CHAT");
        jButtonEnviarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarChatActionPerformed(evt);
            }
        });

        jLabelAdministrador.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabelAdministrador.setForeground(new java.awt.Color(127, 7, 7));
        jLabelAdministrador.setText("Administrador     ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabelAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setMaximumSize(new java.awt.Dimension(129, 26));
        jPanel6.setMinimumSize(new java.awt.Dimension(129, 26));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 17, 16));
        jLabel2.setText("Secretaria    ");
        jLabel2.setMaximumSize(new java.awt.Dimension(129, 23));
        jLabel2.setMinimumSize(new java.awt.Dimension(129, 23));
        jLabel2.setPreferredSize(new java.awt.Dimension(129, 23));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabelConfirmacion.setText("ULTIMO MSM");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblurl, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblurl, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonBorrarChat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditarChat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCargarArchivo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEnviarChat, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabelConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelConfirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBorrarChat, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jButtonEditarChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCargarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButtonEnviarChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBorrarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarChatActionPerformed
        jTextFieldChat.setText(null);
    }//GEN-LAST:event_jButtonBorrarChatActionPerformed

    private void jButtonEnviarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarChatActionPerformed
        Connection conexion = null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String Url = "jdbc:sqlserver://DESKTOP-JD4OQ1D:1433;databaseName=master;user=testjava;password=testjava;";
            conexion=DriverManager.getConnection(Url);
//            JOptionPane.showMessageDialog(null, "CONECCION A BASE DE DATOS EXITOSA");
//            Statement ejecutor = conexion.createStatement();
//            ResultSet respuesta = ejecutor.executeQuery("select * from minivan");
//            String texto= "";
//            while (respuesta.next()) {
//                texto=texto+respuesta.getString("precio")+" "+respuesta.getString("cantidad")+" "+respuesta.getString("nasiento")+"\n" ; 
//            }
//            JOptionPane.showMessageDialog(null,texto);
//            
//            GUARDAR NUEVOS DATOS
            String comando1 ="Insert into Mensajeria (Nombre,Mensaje) values (?,?)";
            PreparedStatement declaracion1 = conexion.prepareStatement(comando1);
            declaracion1.setString(1, jLabelAdministrador.getText());
            declaracion1.setString(2, jTextFieldChat.getText());
            int registro = declaracion1.executeUpdate();
            if (registro > 0) {
//                JOptionPane.showMessageDialog(null,"Se han guardado los archivos correctamente");
            }
//
////            ACTUALIZAR DATOS POR OTROS
//            String comando2 ="Update persona2 set nombre2=? ,apellido2=? ,tel2=? where nombre2=?";
//            PreparedStatement declaracion2 = conexion.prepareStatement(comando2);
//            declaracion2.setString(1, "asdsasdsae");
//            declaracion2.setString(2, "aponcessss");
//            declaracion2.setString(3, "3333333333");
//            declaracion2.setString(4, "OTOOOOOOOO");
//            int resultado2 = declaracion2.executeUpdate();
//            if (resultado2 > 0) {
//                JOptionPane.showMessageDialog(null,"Se ha actualizado lel archivo correctamente");
//            }
////              ELIMINAR FILAS DE NOMBRES IDENTICOS
//              String comando3 ="Delete from persona2 where nombre2 =?";
//              PreparedStatement declaracion3 = conexion.prepareStatement(comando3);
//              declaracion3.setString(1, "Miriammmmm");
//              int resultado3 = declaracion3.executeUpdate();
//              if (resultado3 > 0) {
//                  JOptionPane.showMessageDialog(null,"Se ha eliminado correctamente");
//              }
              
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR AL CONECTAR BASE DE DATOS "+e);
            
        }
        jTextFieldChat.setText(null);
    }//GEN-LAST:event_jButtonEnviarChatActionPerformed

    private void jTextFieldChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChatActionPerformed

    private void jTextFieldChatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldChatKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChatKeyReleased

    private void jTextFieldChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldChatKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        Connection conexion = null;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String Url = "jdbc:sqlserver://DESKTOP-JD4OQ1D:1433;databaseName=master;user=testjava;password=testjava;";
            conexion=DriverManager.getConnection(Url);
    //            JOptionPane.showMessageDialog(null, "CONECCION A BASE DE DATOS EXITOSA");
    //            Statement ejecutor = conexion.createStatement();
    //            ResultSet respuesta = ejecutor.executeQuery("select * from minivan");
    //            String texto= "";
    //            while (respuesta.next()) {
    //                texto=texto+respuesta.getString("precio")+" "+respuesta.getString("cantidad")+" "+respuesta.getString("nasiento")+"\n" ; 
    //            }
    //            JOptionPane.showMessageDialog(null,texto);
    //            
    //            GUARDAR NUEVOS DATOS
            String comando1 ="Insert into Mensajeria (Nombre,Mensaje) values (?,?)";
            PreparedStatement declaracion1 = conexion.prepareStatement(comando1);
            declaracion1.setString(1, jLabelAdministrador.getText());
            declaracion1.setString(2, jTextFieldChat.getText());
            int registro = declaracion1.executeUpdate();
            if (registro > 0) {
    //                JOptionPane.showMessageDialog(null,"Se han guardado los archivos correctamente");
            }
    //
    ////            ACTUALIZAR DATOS POR OTROS
    //            String comando2 ="Update persona2 set nombre2=? ,apellido2=? ,tel2=? where nombre2=?";
    //            PreparedStatement declaracion2 = conexion.prepareStatement(comando2);
    //            declaracion2.setString(1, "asdsasdsae");
    //            declaracion2.setString(2, "aponcessss");
    //            declaracion2.setString(3, "3333333333");
    //            declaracion2.setString(4, "OTOOOOOOOO");
    //            int resultado2 = declaracion2.executeUpdate();
    //            if (resultado2 > 0) {
    //                JOptionPane.showMessageDialog(null,"Se ha actualizado lel archivo correctamente");
    //            }
    ////              ELIMINAR FILAS DE NOMBRES IDENTICOS
    //              String comando3 ="Delete from persona2 where nombre2 =?";
    //              PreparedStatement declaracion3 = conexion.prepareStatement(comando3);
    //              declaracion3.setString(1, "Miriammmmm");
    //              int resultado3 = declaracion3.executeUpdate();
    //              if (resultado3 > 0) {
    //                  JOptionPane.showMessageDialog(null,"Se ha eliminado correctamente");
    //              }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR AL CONECTAR BASE DE DATOS "+e);

        }
        jTextFieldChat.setText(null);
    }
    }//GEN-LAST:event_jTextFieldChatKeyPressed

    private void jButtonCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarArchivoActionPerformed
        
        JFileChooser j = new JFileChooser();
        j.setCurrentDirectory(new File("Imagenes/"));
        int ap = j.showOpenDialog(this);
        
        if(ap == JFileChooser.APPROVE_OPTION){
            ruta = j.getSelectedFile().getAbsolutePath();
            jLabelImagen.setIcon(new ImageIcon(ruta));
            lblurl.setText(ruta);
        }
        
    }//GEN-LAST:event_jButtonCargarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//        Thread hiloP1= new Proceso("proceso 1");  
        Thread hiloP2= new Proceso2("proceso 2");
//        hiloP1.start();
        hiloP2.start();
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainGeneral().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarChat;
    private javax.swing.JButton jButtonCargarArchivo;
    private javax.swing.JButton jButtonEditarChat;
    private javax.swing.JButton jButtonEnviarChat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAdministrador;
    public static javax.swing.JLabel jLabelConfirmacion;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextAreaConversacion;
    private javax.swing.JTextField jTextFieldChat;
    private javax.swing.JLabel lblurl;
    // End of variables declaration//GEN-END:variables
}
